server:
  port: 18082
mybatis-plus:
  mapper-locations: classpath:mapper/sms/**/*.xml
  type-aliases-package: com.atguigu.gmall.sms.entity
  global-config:
    db-config:
      id-type: auto
feign:
  sentinel:
    enabled: true
spring:
  cloud:
    alibaba:
      seata:
        tx-service-group: gmall-tx-group
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.198.128:3306/guli_sms?serverTimezone=GMT%2B8
    username: root
    password: root
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.198.128
    port: 6379