server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
auth:
  jwt:
    pubKeyPath: E:\gmall\rsa\ras.pub
    priKeyPath: E:\gmall\rsa\rsa.pri
    secret: 465as4d894!23#@sad
    cookieName: GMALL-TOKEN
    expire: 180
    unick: unick