server:
  port: 18083
mybatis-plus:
  mapper-locations: classpath:mapper/wms/**/*.xml
  type-aliases-package: com.atguigu.gmall.wms.entity
  global-config:
    db-config:
      id-type: auto  # 默认使用数据库自增
feign:
  sentinel:
    enabled: true
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.198.128:3306/guli_wms?serverTimezone=GMT%2B8
    username: root
    password: root
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.198.128
  rabbitmq:
    virtual-host: /123
    username: 123
    password: 123
    host: 192.168.198.128
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        concurrency: 4
    publisher-confirm-type: correlated
    publisher-returns: true